# Site settings
title: PyroMED
email: info@pyromed.eu
description: "Forest and Fire Ecology in the Mediterranean"
url: "https://pyromed.github.io"
baseurl: "" # Leave empty
twitter_username: username
github_username: pyromed
minimal_mistakes_skin: air
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Collections configuration
collections:
  research:
    output: true
    permalink: /research/:path/

# Include folders
include:
  - _pages
  - _research

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Author Info
author:
  name   : "PyroMED"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Forest and Fire Ecology in the Mediterranean."
  links:
    - label: "Github"
      icon: "fas fa-fw fa-github"
      url: "https://github.com/pyromed"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:info@pyromed.eu"

# Defaults for Layouts
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: research
    values:
      layout: single
      author_profile: true
      share: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
